### ISSUE TITLE
[v2] Update README

### ISSUE THREAD

**Issue by antonioortegajr** [EugeneCodeCamp/EugeneCodeCamp.github.io#8]
With this repo moving to Vue.js the README.md needs a rewrite with the following sections and info in this order.

* About - What is the purpose of this repo?
* Requirements - What would I need before I could add to this repo?
* Install - How do I install  and run on local?
* Development - How would I help develop this project?
* If needed, anything else people should know. For example code gotachs, contacts, or other readme docs in the repo.

**Comment by websupergirl** [comment]
I just realized that I hilariously never updated it on the v1 site from the original theme.

I'm going to assign this one to me to add some text to the issue and then I'll let someone else do the markdown.

**Comment by petrazoid** [comment]
I definitely agree we need a helpful README.md. Does this work for the MVP? Can you drop any other content I should add here?


<img width="488" alt="Screenshot 2020-03-12 at 11 08 53 AM" src="https://user-images.githubusercontent.com/10054415/76553837-0019ad00-6452-11ea-87e7-c5e2ed6c335d.png">
